### ISSUE TITLE
no tooltips

### ISSUE THREAD

**Issue by PumaBlack** [planetguy32/RemainInMotion#168] opened 2015-09-03 19:26 UTC
great mod! Thanks a lot. But i get no tooltips (mouseover), when i am rightklicking an engine - just a small emtpy tooltip-box.

thanks in advance and keep the good work up. I always use the sponsored links for support :)

**Comment by planetguy32** [comment] 2015-09-03 19:29
Screenshot please?

**Comment by planetguy32** [comment] 2015-09-03 19:56
I'm unable to reproduce it in my own game. Are you using a language other than en_US? If so, it might be out of date.

**Comment by PumaBlack** [comment] 2015-09-04 15:54
hi, here is the Screenshot. The language is German, but other mods i run display the english language, if there is no translation. Maybe a bug. thx for the fast respond :)

https://picload.org/view/pgpirwi/bug.jpg.html

**Comment by PumaBlack** [comment] 2015-09-04 15:56
An other major issue is, that all Mobs and Players are slowly push sideways from the moving plattform. Even through walls and fences.

**Comment by planetguy32** [comment] 2015-09-04 16:41
Seems like I need to make my translation code manually fall back to en_US if it can't find a translation in the in-use language. I've fixed it, and am testing it right now.

**Comment by planetguy32** [comment] 2015-09-04 16:52
Update planetguyLib to [version 1.8.1](https://github.com/planetguy32/Utils/releases/tag/v1.8.1).

Physics is a bit flaky on board moving ships, but that's more @da3dsoul's domain than mine. It used to be that entities were locked in place relative to the blocks on board ships, but that made frame ships on continuous mode tricky traps to escape. Maybe locking in place is the right thing to do with non-player entities...

**Comment by PumaBlack** [comment] 2015-09-04 17:53
tooltips solved - thank you!

I tested out the gostmoving of mobs/players while the ship is moving. If i sit on a chair, i get step for step pushed in the oposite direction the ship is moving. After I leave the framework of that ship, i am "siting" still in the air an i have to "stand up" with the left-shift key. After that, i can not take a seat on that chair again, i have to destroy it, and replace it.

https://www.youtube.com/watch?v=ubg2E-8xtyo

here are no such issues, is it possible to adapt some code or ideas? (redstone in motion)

**Comment by planetguy32** [comment] 2015-09-04 18:56
I'd guess that to allow sitting in them, chairs use an invisible entity, since Minecraft only lets you sit on entities, and for some reason RemIM doesn't move it. Maybe locking entities to the carriage like Redstone In Motion did is the best thing to do with non-player entities.

**Comment by da3dsoul** [comment] 2015-09-04 19:46
When you say sideways, do you mean on the same axis as the movement or
perpendicular to it?

**Comment by PumaBlack** [comment] 2015-09-04 20:51
Wenn the Ship moves North, the Player/Mob will move also to north BUT, he slips every block the ship goes to south, until he leaves the ship, even through walls and fences. It seems to me, thast the new position of the Player/Mob is not correctly calculated, If the Block moves from Position 0 to 10, the Player lands on 9, the Next move, the Block goes from 10 to 20, but the Player only goes to Position 18.
And so on, until he glitches though the entire ship and fall of.

Five Blocks. If the Ship moves, the Player (P) slips a bit of the Block:

XXXPX . XXXXX . XXXXX . XXXXX
               XXPXX . XXXXX . XXXXX
                              XPXXX . XXXXX . XXXXX
                                             PXXXX . XXXXX . XXXXX
                                                         P XXXXX . XXXXX . XXXXX

and he falls of.

I hope, i cloud explain it without a Video ;)

**Comment by da3dsoul** [comment] 2015-09-04 20:56
It's a lag issue, actually. RiM uses a lot of power, and the game will skip
ticks, those ticks move the entity. I've tried to make it account for the
lag, but the best I did was make it close and make collision mostly work.
If you have a small wall and stand two blocks ahead of it, you won't fall
off.

**Comment by planetguy32** [comment] 2015-09-12 03:37
Sounds like the original issue is done, so unless anyone objects I'll close it.

**Closed by planetguy32** 2015-09-12 03:37 UTC
