### ISSUE TITLE
Client Crash when interacting with engines

### ISSUE THREAD

**Issue by NonniT** [planetguy32/RemainInMotion#157] opened 2015-07-21 15:31 UTC
I can interact once with an engine, but any time I open the panel after that, I get a full client crash. Applying redstone signals etc also fail to move the frame I've built. I'm running a slightly modified version of FTB Infinity (RiM and a few others added).

Here's a copy of the crash log. Please let me know if you could use any more info :)

http://pastebin.com/wiXE1QZ8

**Comment by planetguy32** [comment] 2015-07-21 16:03
I'm having trouble replicating this. Which block did you use? Did you change any settings in the GUI?

**Comment by NonniT** [comment] 2015-07-21 16:20
The only setting box clicked in the GUI was to travel East.

I have tried with both the Directional Carriage Engine, and by spawning in a Carriage Engine and trying that to no avail. This is on a template carriage.

**Comment by NonniT** [comment] 2015-07-21 16:21
And thanks for looking into this! :)

**Comment by planetguy32** [comment] 2015-07-21 16:21
Is this on a dedicated server?

**Comment by NonniT** [comment] 2015-07-21 16:26
Yep. Dedicated, local server.

**Comment by planetguy32** [comment] 2015-07-21 17:15
That looks like the server sent a packet referring to an inventory slot that doesn't exist, so perhaps it was meant for a GUI you exited and the delay broke it - that would make this crash simply bad luck. Can you consistently reproduce the crash?

**Comment by NonniT** [comment] 2015-07-21 17:24
Yep. It happens every time I open the GUI of the Engine. I can access it once after placing it, after which all further attempts to access it crash the client. The only way to interact with it once more is to reboot the server.

**Comment by da3dsoul** [comment] 2015-07-21 19:33
From what I can tell, there is an error in the player inventory implementation into the gui. There are no other slots in the gui. I'll look into it today.

**Comment by planetguy32** [comment] 2015-07-21 19:42
I've still been unable to reproduce it running only the mods in my development workspace, so I'm guessing it's a cross-mod interaction, perhaps with HoloInventory or InvTweaks.

**Comment by NonniT** [comment] 2015-07-21 20:06
Just tried it without InvTweaks or HoloInventory (removed both from the server and client) - still experiencing the same thing. Weird. Thanks for looking into it though. Can't think what other information may be useful.

**Comment by da3dsoul** [comment] 2015-07-21 20:12
The dedicated server info is likely all I'll need. I have a lot of experience with networking. Plus, the log from mantle tells me quite nicely what mods you are using.

**Comment by NonniT** [comment] 2015-07-21 20:37
Sorry, little bit of a rookie to this. I'm basically just running a local version of FTB Infinity server + client, with a few minor config changes and a few mods thrown on top.

The server logs from the time where my client crashes shows:

[20:56:01] [Server thread/INFO]: Diagoras[/192.168.0.5:61655] logged in with entity id 9944 at (746.5824801038533, 140.0, 620.882647208989)
[20:56:01] [Server thread/INFO]: Diagoras joined the game
[20:56:48] [Server thread/INFO]: Diagoras lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[20:56:48] [Server thread/INFO]: Diagoras left the game

Are there any server commands or anything like that which would produce any useful logs?

Thanks for the help guys :)

**Comment by da3dsoul** [comment] 2015-07-21 22:29
No I was saying the log was adequate and I have all I need for now

**Comment by TheQuantumGeneral** [comment] 2015-07-22 13:29
I am also crashing when opening any engine GUI in a server environment. Works fine in singleplayer.

log: http://pastebin.com/4pUkBWhP

**Comment by planetguy32** [comment] 2015-07-22 15:13
I'd guess this is a cross-mod interaction, because it is stubbornly not happening for me. Can you reproduce it with less mods?

**Comment by NonniT** [comment] 2015-07-22 15:50
Any suggestion on what mods to try dropping / what ones you know to be fine?

I'll try a plain FTB Infinity install with RiM on top later when I have some spare time! :) Thanks.

**Comment by planetguy32** [comment] 2015-07-22 16:03
In my workspace I have HoloInventory, BluePower, ComputerCraft, Applied Energistics, Buildcraft, Thermal Expansion, ChickenChunks, ForgeMultipart, and their dependencies.

**Comment by da3dsoul** [comment] 2015-07-22 16:13
It's not a mod thing. It's a server thing.

**Comment by planetguy32** [comment] 2015-07-22 16:27
I've tried it on a server and have been able to use GUIs repeatedly with no problems at all, so I'm guessing it's a mod sending the packets.

**Comment by planetguy32** [comment] 2015-07-23 17:00
It doesn't seem to be related to a recent Forge change either, since I couldn't reproduce it on the current recommended version, 1448.

**Comment by aionys** [comment] 2015-07-26 08:52
I can confirm this.

Process:
I started up the server and the client, logged in, typed "Right-clicking Carriage Engine now", right-clicked on the Engine and got the GUI, didn't crash, put the game into fullscreen, typed "And Again" into chat, right-clicked and crashed.

The log is too long for Pastebin, so I uploaded the server log, the client log, and the client crash report to Google Drive:
https://drive.google.com/folderview?id=0B2q7KyznfswHMkhLbnJncW5mbms&usp=sharing

All the relevant information, Java version, FML version, installed mods, and so on, should be in the crash report. If you need any further information, just tell me what it is.

**Comment by AlphaSparqy** [comment] 2015-08-13 08:48
Same thing here.

FTB Infinity with this and Opis added.  I'm playing all by myself.

The stack trace is identical to Nonnit's too.

http://pastebin.com/k0k5s9ET

**Comment by TheQuantumGeneral** [comment] 2015-08-13 08:54
I was having this issue previously, and i'm not sure if the update fixed it or if I removed some mod that was conflicting, but I no longer have this issue on build 2.8.1

**Comment by AlphaSparqy** [comment] 2015-08-13 09:32
Did a little more research, and found some commonalities with wearing the Draconic Evolution armor (it uses an inventory for holding enchants), and without wearing it, I don't get the client crash.

However, I do now get never ending block lag, when trying to activate a support frame, that's holding an inactive bigreactor reactor & turbines.

**Comment by planetguy32** [comment] 2015-08-16 04:27
Thanks for your updates, they should be useful in narrowing down this issue to less than all of FTB Infinity. I'll look into it tomorrow, after I get some sleep.

**Comment by planetguy32** [comment] 2015-08-16 17:52
I tried right-clicking a carriage drive while holding a TCon+ITweaks pickaxe on multiplayer, and it didn't crash.

**Comment by aionys** [comment] 2015-08-16 18:07
For my part, I was testing with an empty hand, so I don't think the problem is related to what the user is holding when attempting to open the gui.

**Comment by planetguy32** [comment] 2015-08-16 18:10
When you were testing it, what did you have in your inventories?

**Comment by aionys** [comment] 2015-08-16 18:19
Your screwdriver, MachineMuse Powersuit armor and the Power Fist, Tinker's pickaxe and hammer, a TE wrench, an EnderChest ender pouch, and some berries. Couple of red hearts from TC too, IIRC.

**Comment by aionys** [comment] 2015-08-16 18:27
To be completely honest, I preferred the pre-GUI version better, and not just because I don't like that the motor and engine were combined into one item.

**Comment by lehjr** [comment] 2015-10-28 19:35
@planetguy32  @da3dsoul 
I've been looking at this a bit in a dev environment and I noticed bindPlayerInventory in ContainerPrefab never gets called, even when no crash occurs, but gets skipped over instead. I'm just not sure why.

**Comment by planetguy32** [comment] 2015-10-30 03:38
I'm pretty sure bindPlayerInventory shouldn't be called anyway. (Maybe MPS/whatever was expecting it to be called?) What bindPlayerInventory does is it makes space for the player's inventory slots, but we skip that since our GUIs don't actually show the player's inventory.

**Comment by lehjr** [comment] 2015-10-30 11:36
Isn't it called here: https://github.com/planetguy32/Utils/blob/29676411aa70e58fb853ead143c71358fbd107b2/src/main/java/me/planetguy/lib/prefab/ContainerPrefab.java#L15

**Comment by planetguy32** [comment] 2015-10-30 13:36
It is called there, but at https://github.com/planetguy32/RemainInMotion/blob/master/src/main/java/me/planetguy/remaininmotion/drive/gui/ContainerDrive.java we override it with an empty method.

**Comment by lehjr** [comment] 2015-10-30 13:38
Ah, I see. The reason I mentioned it was I remembered this bug from in Archimedes Ships. It was fixed in the updated and reworked fork Archimedes Ships Plus here: https://github.com/darkevilmac/archimedes-ships-plus/commit/99d7de0296dd430bc7bbe8ab395489f2b94d8453

**Comment by lehjr** [comment] 2015-10-30 14:12
Also, unrelated, but when I was playing with RIM in my dev environment I added this file for the sake of convenience (to get rid of the planetguy lib 1.9 not found at run time):

me.planetguy.lib/package-info.java:
/**
 * PlanetguyLib
 */
@cpw.mods.fml.common.API(
        owner = "planetguyLib",
        provides = "planetguyLib",
        apiVersion = "1.9")
package me.planetguy.lib;;

**Comment by lehjr** [comment] 2015-10-30 15:53
Just for kicks, I tried commenting that bindPlayerInventory override in https://github.com/planetguy32/RemainInMotion/blob/master/src/main/java/me/planetguy/remaininmotion/drive/gui/ContainerDrive.java and I don't get the crash anymore

**Comment by planetguy32** [comment] 2015-10-30 17:36
Interesting. Do the player's inventory slots show up in the GUI if you do that?

**Comment by lehjr** [comment] 2015-10-30 17:39
everything in the player's inventory shows up on a layer above the GUI. Let me see I can grab a screenshot real quick

**Comment by lehjr** [comment] 2015-10-30 17:44
![2015-10-30_13 44 00](https://cloud.githubusercontent.com/assets/1084367/10853424/555f9be2-7f0c-11e5-8777-9d7bdeb5a3e0.png)

**Comment by planetguy32** [comment] 2015-10-30 17:57
Does that commit fix things?

**Comment by lehjr** [comment] 2015-10-30 18:11
LOL! But yes, it does. I have an unreleased version of MPS with addons integrated and it is working here instead of the initial crash. If it's fixed for that it "should" be for everything else.

**Comment by planetguy32** [comment] 2015-10-30 18:22
Fix published in release 2.8.8, available on the Github release page on CurseForge.

**Closed by planetguy32** 2015-10-30 18:22 UTC
Labels: bug
